#!/bin/bash -x

pushd ~/railsapp

bundle install --path=~/local.bundle > /dev/null
bundle exec rake db:migrate > /dev/null
bundle exec rails s & > /dev/null

sleep 10

while true
do
    for i in {1..10}
    do
	curl http://localhost:3000/people > /dev/null
    done
    bundle exec rake > /dev/null
done

popd
